# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8247cf7cf3a89d1c861d2661a016b097dd1b83a81d73626030385cab763ce04a9f279d87444f1b5915f2b4f8a37377a5b7ba676752fba476a125c1fa9f7b27d

test:
  secret_key_base: b5f4f3b024402748055237947e0c60ba376431b3b766233f3b06a6a95b55882d75eeaad70e56bcf0c027f641a0cd52a6c64edd9148505e60a638062a3ada7dc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
